"""Add Turkish (name_tr) translations to foods.csv — no API needed."""
import csv, io, os

TRANSLATIONS = {
    # === Protein Sources ===
    "Chicken breast, boneless skinless, cooked": "Tavuk göğsü, derisiz kemiksiz, pişmiş",
    "Chicken breast, boneless skinless, raw": "Tavuk göğsü, derisiz kemiksiz, çiğ",
    "Chicken thigh, boneless skinless, cooked": "Tavuk but, derisiz kemiksiz, pişmiş",
    "Chicken thigh, boneless skinless, raw": "Tavuk but, derisiz kemiksiz, çiğ",
    "Chicken drumstick, skin on, cooked": "Tavuk incik, derili, pişmiş",
    "Chicken drumstick, skin on, raw": "Tavuk incik, derili, çiğ",
    "Chicken wing, skin on, cooked": "Tavuk kanadı, derili, pişmiş",
    "Turkey breast, boneless skinless, cooked": "Hindi göğsü, derisiz kemiksiz, pişmiş",
    "Turkey breast, boneless skinless, raw": "Hindi göğsü, derisiz kemiksiz, çiğ",
    "Turkey thigh, cooked": "Hindi but, pişmiş",
    "Ground turkey, 85% lean, cooked": "Kıyma hindi, %85 yağsız, pişmiş",
    "Ground turkey, 93% lean, cooked": "Kıyma hindi, %93 yağsız, pişmiş",
    "Egg, whole, raw": "Yumurta, tam, çiğ",
    "Egg, whole, boiled": "Yumurta, tam, haşlanmış",
    "Egg, whole, fried": "Yumurta, tam, kızartılmış",
    "Egg, scrambled": "Çırpılmış yumurta",
    "Egg white, raw": "Yumurta akı, çiğ",
    "Egg yolk, raw": "Yumurta sarısı, çiğ",
    "Salmon, Atlantic, cooked": "Somon, Atlantik, pişmiş",
    "Salmon, Atlantic, raw": "Somon, Atlantik, çiğ",
    "Tuna, canned in water, drained": "Ton balığı, su içinde konserve, süzülmüş",
    "Tuna, fresh, cooked": "Ton balığı, taze, pişmiş",
    "Cod, cooked": "Morina, pişmiş",
    "Tilapia, cooked": "Tilapya, pişmiş",
    "Shrimp, cooked": "Karides, pişmiş",
    "Mahi-mahi, cooked": "Mahi-mahi balığı, pişmiş",
    "Halibut, cooked": "Pisi balığı, pişmiş",
    "Sardines, canned in oil, drained": "Sardalya, yağ içinde konserve, süzülmüş",
    "Ground beef, 85% lean, cooked": "Dana kıyma, %85 yağsız, pişmiş",
    "Ground beef, 90% lean, cooked": "Dana kıyma, %90 yağsız, pişmiş",
    "Ground beef, 93% lean, cooked": "Dana kıyma, %93 yağsız, pişmiş",
    "Ground beef, 95% lean, cooked": "Dana kıyma, %95 yağsız, pişmiş",
    "Beef ribeye steak, cooked": "Dana antrikot biftek, pişmiş",
    "Beef sirloin steak, cooked": "Dana kontrfile biftek, pişmiş",
    "Beef filet mignon, cooked": "Dana filetosu, pişmiş",
    "Beef chuck roast, cooked": "Dana omuz kavurması, pişmiş",
    "Beef ground round, 80% lean, cooked": "Dana toprak kıyma, %80 yağsız, pişmiş",
    "Pork loin, cooked": "Domuz beli, pişmiş",
    "Pork chop, center loin, cooked": "Domuz pirzolası, pişmiş",
    "Pork tenderloin, cooked": "Domuz filetosu, pişmiş",
    "Bacon, pan fried": "Pastırma (domuz), tavada kızartılmış",
    "Pork sausage, cooked": "Domuz sosisi, pişmiş",
    "Tofu, firm, raw": "Tofu, sert, çiğ",
    "Tofu, silken, raw": "Tofu, ipeksi, çiğ",
    "Tempeh, cooked": "Tempeh, pişmiş",
    "Seitan, cooked": "Seitan, pişmiş",
    "Chicken patty, cooked": "Tavuk köfte, pişmiş",
    "Fish fillet, battered and fried": "Balık fileto, unlu kızartma",
    "Beef hot dog, Hebrew National": "Dana sosis (hot dog)",
    "Turkey hot dog": "Hindi sosisi (hot dog)",
    "Deli ham, sliced": "Jambon, dilimlenmiş",
    "Deli roast beef, sliced": "Dana rosto, dilimlenmiş",
    "Deli turkey, sliced": "Hindi şarküteri, dilimlenmiş",
    "Pepperoni, sliced": "Pepperoni, dilimlenmiş",
    "Salami, sliced": "Salam, dilimlenmiş",
    "Bologna, sliced": "Bologna sosis, dilimlenmiş",
    "Beef jerky, original": "Kurutulmuş dana eti",
    "Chicken jerky": "Kurutulmuş tavuk eti",
    "Whey protein powder, vanilla": "Whey protein tozu, vanilyalı",
    "Whey protein powder, chocolate": "Whey protein tozu, çikolatalı",
    "Casein protein powder, vanilla": "Kazein protein tozu, vanilyalı",
    "Plant-based protein powder, vanilla": "Bitkisel protein tozu, vanilyalı",
    "Ground chicken, 93% lean, cooked": "Tavuk kıyma, %93 yağsız, pişmiş",
    "Chicken breast, with skin, cooked": "Tavuk göğsü, derili, pişmiş",
    "Duck breast, cooked": "Ördek göğsü, pişmiş",
    "Lamb chop, cooked": "Kuzu pirzolası, pişmiş",
    "Lamb ground, cooked": "Kuzu kıyma, pişmiş",
    "Venison, cooked": "Geyik eti, pişmiş",
    "Elk, cooked": "Elk eti, pişmiş",
    "Bison, cooked": "Bizon eti, pişmiş",
    "Tuna salad (with mayo)": "Ton balığı salatası (mayonezli)",
    "Chicken salad (with mayo)": "Tavuk salatası (mayonezli)",
    "Egg salad": "Yumurta salatası",
    "Beef liver, cooked": "Dana karaciğeri, pişmiş",
    "Chicken liver, cooked": "Tavuk ciğeri, pişmiş",
    "Pork liver, cooked": "Domuz karaciğeri, pişmiş",
    "Oysters, cooked": "İstiridye, pişmiş",
    "Clams, cooked": "Midye iskeleti, pişmiş",
    "Scallops, cooked": "Deniz tarağı, pişmiş",
    "Mussels, cooked": "Midye, pişmiş",
    "Crab, cooked": "Yengeç, pişmiş",
    "Lobster, cooked": "Istakoz, pişmiş",
    "Anchovies, canned": "Hamsi, konserve",
    "Mackerel, Atlantic, cooked": "Uskumru, Atlantik, pişmiş",
    "Herring, Atlantic, cooked": "Ringa balığı, Atlantik, pişmiş",
    "Trout, rainbow, cooked": "Alabalık, pişmiş",
    "Catfish, channel, cooked": "Yayın balığı, pişmiş",
    "Flounder, cooked": "Dil balığı, pişmiş",
    "Snapper, red, cooked": "Kırmızı balık, pişmiş",
    "Swordfish, cooked": "Kılıç balığı, pişmiş",
    "Striped bass, cooked": "Çizgili levrek, pişmiş",
    "Mussels, steamed": "Midye, buharda pişmiş",
    "Sausage patty, pork, cooked": "Domuz sosis köfte, pişmiş",
    "Italian sausage, cooked": "İtalyan sosisi, pişmiş",
    "Kielbasa sausage": "Kielbasa sosis",
    "Bratwurst sausage, cooked": "Bratwurst sosis, pişmiş",
    "Breakfast sausage links, cooked": "Kahvaltı sosisi, pişmiş",
    "Spam": "Spam konserve eti",
    "Corned beef, cooked": "Corned beef, pişmiş",
    "Liverwurst": "Ciğer sosisi",

    # === Dairy ===
    "Milk, whole, 3.7% fat": "Süt, tam yağlı, %3.7",
    "Milk, 2% fat": "Süt, %2 yağlı",
    "Milk, 1% fat": "Süt, %1 yağlı",
    "Milk, skim": "Süt, yağsız",
    "Milk, raw": "Süt, çiğ",
    "Buttermilk, low fat": "Ayran (yayıkaltı), az yağlı",
    "Almond milk, unsweetened": "Badem sütü, şekersiz",
    "Almond milk, sweetened": "Badem sütü, şekerli",
    "Oat milk, unsweetened": "Yulaf sütü, şekersiz",
    "Oat milk, original": "Yulaf sütü, orijinal",
    "Soy milk, unsweetened": "Soya sütü, şekersiz",
    "Soy milk, original": "Soya sütü, orijinal",
    "Cashew milk, unsweetened": "Kaju sütü, şekersiz",
    "Coconut milk, full fat canned": "Hindistan cevizi sütü, tam yağlı konserve",
    "Coconut milk, light canned": "Hindistan cevizi sütü, light konserve",
    "Cheddar cheese, sharp": "Çedar peyniri, sert",
    "Cheddar cheese, mild": "Çedar peyniri, yumuşak",
    "Mozzarella cheese, whole milk": "Mozzarella peyniri, tam yağlı",
    "Mozzarella cheese, low moisture": "Mozzarella peyniri, düşük nemli",
    "Mozzarella cheese, part skim": "Mozzarella peyniri, yarı yağsız",
    "Swiss cheese": "İsviçre peyniri",
    "Provolone cheese": "Provolone peyniri",
    "Parmesan cheese, grated": "Parmesan peyniri, rendelenmiş",
    "Parmesan cheese, block": "Parmesan peyniri, blok",
    "Feta cheese": "Beyaz peynir (feta)",
    "Gouda cheese": "Gouda peyniri",
    "Brie cheese": "Brie peyniri",
    "Blue cheese": "Mavi peynir",
    "Cream cheese": "Krem peynir",
    "Ricotta cheese, whole milk": "Ricotta peyniri, tam yağlı",
    "Ricotta cheese, part skim": "Ricotta peyniri, yarı yağsız",
    "Cottage cheese, 4% fat": "Lor peyniri, %4 yağlı",
    "Cottage cheese, 1% fat": "Lor peyniri, %1 yağlı",
    "Cottage cheese, 2% fat": "Lor peyniri, %2 yağlı",
    "American cheese, processed": "Amerikan peyniri, işlenmiş",
    "Velveeta cheese": "Velveeta peyniri",
    "String cheese, mozzarella": "Tel peyniri, mozzarella",
    "Butter, salted": "Tereyağı, tuzlu",
    "Butter, unsalted": "Tereyağı, tuzsuz",
    "Ghee": "Sade yağ (ghee)",
    "Heavy cream, whipping": "Ağır krema",
    "Sour cream": "Ekşi krema",
    "Whipped cream": "Çırpılmış krema",
    "Crème fraîche": "Crème fraîche",
    "Greek yogurt, plain, full fat": "Yunan yoğurdu, sade, tam yağlı",
    "Greek yogurt, plain, low fat": "Yunan yoğurdu, sade, az yağlı",
    "Greek yogurt, plain, nonfat": "Yunan yoğurdu, sade, yağsız",
    "Greek yogurt, vanilla, low fat": "Yunan yoğurdu, vanilyalı, az yağlı",
    "Yogurt, plain, whole milk": "Yoğurt, sade, tam yağlı",
    "Yogurt, plain, low fat": "Yoğurt, sade, az yağlı",
    "Yogurt, plain, nonfat": "Yoğurt, sade, yağsız",
    "Yogurt, vanilla, low fat": "Yoğurt, vanilyalı, az yağlı",
    "Yogurt, fruit, low fat": "Yoğurt, meyveli, az yağlı",
    "Kefir, plain, full fat": "Kefir, sade, tam yağlı",
    "Kefir, plain, low fat": "Kefir, sade, az yağlı",
    "Kefir, fruit, full fat": "Kefir, meyveli, tam yağlı",
    "Ice cream, vanilla": "Dondurma, vanilyalı",
    "Ice cream, chocolate": "Dondurma, çikolatalı",
    "Ice cream, strawberry": "Dondurma, çilekli",
    "Frozen yogurt, vanilla": "Dondurulmuş yoğurt, vanilyalı",
    "Frozen yogurt, chocolate": "Dondurulmuş yoğurt, çikolatalı",
    "Rice milk": "Pirinç sütü",
    "Chocolate milk, whole": "Çikolatalı süt, tam yağlı",
    "Chocolate milk, low fat": "Çikolatalı süt, az yağlı",

    # === Grains & Bread ===
    "White rice, long grain, cooked": "Beyaz pirinç, uzun taneli, pişmiş",
    "White rice, short grain, cooked": "Beyaz pirinç, kısa taneli, pişmiş",
    "Brown rice, long grain, cooked": "Esmer pirinç, uzun taneli, pişmiş",
    "Jasmine rice, cooked": "Yasemin pirinci, pişmiş",
    "Basmati rice, cooked": "Basmati pirinç, pişmiş",
    "Arborio rice, cooked": "Arborio pirinç, pişmiş",
    "Wild rice, cooked": "Yabani pirinç, pişmiş",
    "Black rice, cooked": "Siyah pirinç, pişmiş",
    "Quinoa, cooked": "Kinoa, pişmiş",
    "Buckwheat, cooked": "Karabuğday, pişmiş",
    "Couscous, cooked": "Kuskus, pişmiş",
    "Bulgar wheat, cooked": "Bulgur, pişmiş",
    "Millet, cooked": "Darı, pişmiş",
    "Amaranth, cooked": "Amarant, pişmiş",
    "Teff, cooked": "Teff, pişmiş",
    "Farro, cooked": "Farro, pişmiş",
    "Oats, rolled, dry": "Yulaf ezmesi, kuru",
    "Oats, instant, prepared with water": "Anlık yulaf, suyla hazırlanmış",
    "Oats, old fashioned, dry": "Geleneksel yulaf, kuru",
    "Oatmeal, prepared with water": "Yulaf lapası, suyla hazırlanmış",
    "Pasta, spaghetti, cooked": "Makarna, spagetti, pişmiş",
    "Pasta, penne, cooked": "Makarna, penne, pişmiş",
    "Pasta, elbow, cooked": "Makarna, dirsek, pişmiş",
    "Pasta, whole wheat, cooked": "Makarna, tam buğday, pişmiş",
    "Pasta, egg noodles, cooked": "Yumurtalı erişte, pişmiş",
    "Pasta, lasagna noodles, cooked": "Lazanya, pişmiş",
    "Granola, low fat": "Granola, az yağlı",
    "Granola, regular": "Granola, normal",
    "Granola, low sugar": "Granola, az şekerli",
    "Cereal, Cheerios": "Mısır gevreği, Cheerios",
    "Cereal, Fruity Pebbles": "Mısır gevreği, Fruity Pebbles",
    "Cereal, Frosted Flakes": "Mısır gevreği, Frosted Flakes",
    "Cereal, Lucky Charms": "Mısır gevreği, Lucky Charms",
    "Cereal, Raisin Bran": "Mısır gevreği, Raisin Bran",
    "Cereal, All Bran": "Mısır gevreği, All Bran",
    "Cereal, Special K": "Mısır gevreği, Special K",
    "Cereal, Cinnamon Toast Crunch": "Mısır gevreği, Cinnamon Toast Crunch",
    "Cereal, Honey Nut Cheerios": "Mısır gevreği, Ballı Cheerios",
    "Muesli, with nuts": "Müsli, fındıklı",
    "Barley, pearled, cooked": "Arpa, inci, pişmiş",
    "Cornmeal, yellow, dry": "Mısır unu, sarı, kuru",
    "Popcorn, air-popped": "Patlamış mısır, havalı",
    "Popcorn, oil-popped": "Patlamış mısır, yağlı",
    "Popcorn, caramel": "Patlamış mısır, karamelli",
    "Pretzel, hard": "Pretzel, sert",
    "Pretzel, soft": "Pretzel, yumuşak",
    "Bran muffin": "Kepekli muffin",
    "Banana muffin": "Muzlu muffin",
    "Blueberry muffin": "Yaban mersinli muffin",
    "Apple cinnamon muffin": "Elmalı tarçınlı muffin",
    "Cornbread muffin": "Mısır ekmeği muffin",

    # Bread variants (same base name in CSV)
    "Bread": "Ekmek",
    "Bagel": "Simit (bagel)",
    "English muffin": "İngiliz muffin",
    "Croissant": "Kruvasan",
    "Tortilla": "Tortilla",
    "Pita bread": "Pide ekmeği",
    "Rice cakes": "Pirinç keki",
    "Crackers": "Kraker",
    "Pancake": "Krep (pancake)",
    "Waffle": "Waffle",

    # === Fruits ===
    "Banana": "Muz",
    "Apple, Gala": "Elma, Gala",
    "Apple, Granny Smith": "Elma, Granny Smith",
    "Apple, Honeycrisp": "Elma, Honeycrisp",
    "Orange, navel": "Portakal, göbekli",
    "Orange, Florida": "Portakal, Florida",
    "Strawberry": "Çilek",
    "Blueberry": "Yaban mersini",
    "Raspberry": "Ahududu",
    "Blackberry": "Böğürtlen",
    "Grape, red": "Üzüm, kırmızı",
    "Grape, green": "Üzüm, yeşil",
    "Watermelon": "Karpuz",
    "Cantaloupe": "Kavun",
    "Honeydew": "Bal kavunu",
    "Mango": "Mango",
    "Pineapple": "Ananas",
    "Peach": "Şeftali",
    "Pear": "Armut",
    "Plum": "Erik",
    "Cherry": "Kiraz",
    "Kiwi, golden": "Kivi, altın",
    "Kiwi, green": "Kivi, yeşil",
    "Papaya": "Papaya",
    "Coconut, raw": "Hindistan cevizi, taze",
    "Coconut, shredded, unsweetened": "Hindistan cevizi, rendelenmiş, şekersiz",
    "Coconut, shredded, sweetened": "Hindistan cevizi, rendelenmiş, şekerli",
    "Avocado": "Avokado",
    "Lemon": "Limon",
    "Lime": "Misket limonu",
    "Grapefruit, pink": "Greyfurt, pembe",
    "Grapefruit, white": "Greyfurt, beyaz",
    "Tangerine": "Mandalina",
    "Pomegranate": "Nar",
    "Fig, fresh": "İncir, taze",
    "Date, Medjool": "Hurma, Medjool",
    "Date, Deglet Noor": "Hurma, Deglet Noor",
    "Raisin": "Kuru üzüm",
    "Cranberry, dried": "Kızılcık, kurutulmuş",
    "Apricot, dried": "Kayısı, kurutulmuş",
    "Prune": "Kuru erik",
    "Currants, black": "Kuş üzümü, siyah",
    "Currants, red": "Kuş üzümü, kırmızı",
    "Gooseberry": "Bektaşi üzümü",
    "Passionfruit": "Çarkıfelek meyvesi",
    "Persimmon": "Hurma (trabzon hurması)",
    "Lychee": "Liçi",
    "Dragon fruit": "Ejder meyvesi",
    "Guava": "Guava",
    "Jackfruit": "Jackfruit",
    "Mulberry": "Dut",
    "Loganberry": "Loganberry",
    "Boysenberry": "Boysenberry",
    "Tangerine juice, fresh": "Mandalina suyu, taze",
    "Orange juice, fresh": "Portakal suyu, taze",
    "Apple juice, unsweetened": "Elma suyu, şekersiz",
    "Grape juice, unsweetened": "Üzüm suyu, şekersiz",
    "Cranberry juice, unsweetened": "Kızılcık suyu, şekersiz",
    "Pomegranate juice": "Nar suyu",
    "Grapefruit juice": "Greyfurt suyu",
    "Pineapple juice": "Ananas suyu",
    "Mango juice": "Mango suyu",
    "Papaya juice": "Papaya suyu",
    "Watermelon juice, fresh": "Karpuz suyu, taze",
    "Watermelon juice": "Karpuz suyu",
    "Mixed berry juice": "Karışık meyve suyu",
    "Acai berry juice": "Açaı meyvesi suyu",
    "Tart cherry juice": "Vişne suyu",

    # === Vegetables ===
    "Broccoli, raw": "Brokoli, çiğ",
    "Broccoli, cooked": "Brokoli, pişmiş",
    "Spinach, raw": "Ispanak, çiğ",
    "Spinach, cooked": "Ispanak, pişmiş",
    "Kale, raw": "Kara lahana, çiğ",
    "Kale, cooked": "Kara lahana, pişmiş",
    "Lettuce, romaine, raw": "Marul, romaine, çiğ",
    "Lettuce, iceberg, raw": "Marul, iceberg, çiğ",
    "Lettuce, butterhead, raw": "Marul, yağ başlı, çiğ",
    "Arugula, raw": "Roka, çiğ",
    "Watercress, raw": "Su teresi, çiğ",
    "Bok choy, raw": "Bok choy, çiğ",
    "Swiss chard, raw": "Pazı, çiğ",
    "Collard greens, raw": "Yaprak lahana, çiğ",
    "Tomato, raw": "Domates, çiğ",
    "Tomato, cooked": "Domates, pişmiş",
    "Tomato, cherry": "Cherry domates",
    "Tomato, sun-dried": "Güneşte kurutulmuş domates",
    "Onion, yellow, raw": "Soğan, sarı, çiğ",
    "Onion, yellow, cooked": "Soğan, sarı, pişmiş",
    "Onion, red, raw": "Soğan, kırmızı, çiğ",
    "Onion, white, raw": "Soğan, beyaz, çiğ",
    "Onion, sweet, raw": "Soğan, tatlı, çiğ",
    "Garlic, raw": "Sarımsak, çiğ",
    "Garlic, cooked": "Sarımsak, pişmiş",
    "Bell pepper, red, raw": "Kırmızı biber, çiğ",
    "Bell pepper, green, raw": "Yeşil biber, çiğ",
    "Bell pepper, yellow, raw": "Sarı biber, çiğ",
    "Bell pepper, orange, raw": "Turuncu biber, çiğ",
    "Carrot, raw": "Havuç, çiğ",
    "Carrot, cooked": "Havuç, pişmiş",
    "Carrot, baby": "Bebek havuç",
    "Celery, raw": "Kereviz sapı, çiğ",
    "Celery, cooked": "Kereviz sapı, pişmiş",
    "Cucumber, raw": "Salatalık, çiğ",
    "Cucumber, with skin": "Salatalık, kabuklu",
    "Zucchini, raw": "Kabak, çiğ",
    "Zucchini, cooked": "Kabak, pişmiş",
    "Mushroom, raw": "Mantar, çiğ",
    "Mushroom, white, raw": "Beyaz mantar, çiğ",
    "Mushroom, cremini, raw": "Cremini mantar, çiğ",
    "Mushroom, portobello, raw": "Portobello mantar, çiğ",
    "Mushroom, shiitake, cooked": "Shiitake mantar, pişmiş",
    "Mushroom, oyster, cooked": "İstiridye mantarı, pişmiş",
    "Cauliflower, raw": "Karnabahar, çiğ",
    "Cauliflower, cooked": "Karnabahar, pişmiş",
    "Asparagus, raw": "Kuşkonmaz, çiğ",
    "Asparagus, cooked": "Kuşkonmaz, pişmiş",
    "Green beans, raw": "Taze fasulye, çiğ",
    "Green beans, cooked": "Taze fasulye, pişmiş",
    "Peas, green, raw": "Bezelye, çiğ",
    "Peas, green, cooked": "Bezelye, pişmiş",
    "Snap peas, raw": "Şeker bezelye, çiğ",
    "Snap peas, cooked": "Şeker bezelye, pişmiş",
    "Snow peas, raw": "Kar bezelye, çiğ",
    "Corn, yellow, raw": "Mısır, sarı, çiğ",
    "Corn, yellow, cooked": "Mısır, sarı, pişmiş",
    "Potato, white, baked with skin": "Patates, beyaz, kabuklu fırında",
    "Potato, white, boiled": "Patates, beyaz, haşlanmış",
    "Potato, red, baked with skin": "Patates, kırmızı, kabuklu fırında",
    "Potato, russet, baked": "Patates, russet, fırında",
    "Sweet potato, baked": "Tatlı patates, fırında",
    "Sweet potato, boiled": "Tatlı patates, haşlanmış",
    "Yam, baked": "Yam kökü, fırında",
    "Butternut squash, raw": "Bal kabağı, çiğ",
    "Butternut squash, cooked": "Bal kabağı, pişmiş",
    "Acorn squash, cooked": "Palamut kabağı, pişmiş",
    "Spaghetti squash, cooked": "Spagetti kabağı, pişmiş",
    "Eggplant, raw": "Patlıcan, çiğ",
    "Eggplant, cooked": "Patlıcan, pişmiş",
    "Cabbage, green, raw": "Lahana, yeşil, çiğ",
    "Cabbage, red, raw": "Lahana, kırmızı, çiğ",
    "Cabbage, Napa, raw": "Çin lahanası, çiğ",
    "Brussels sprouts, raw": "Brüksel lahanası, çiğ",
    "Brussels sprouts, cooked": "Brüksel lahanası, pişmiş",
    "Artichoke, raw": "Enginar, çiğ",
    "Artichoke, cooked": "Enginar, pişmiş",
    "Beet, raw": "Pancar, çiğ",
    "Beet, cooked": "Pancar, pişmiş",
    "Radish, raw": "Turp, çiğ",
    "Turnip, raw": "Şalgam, çiğ",
    "Turnip, cooked": "Şalgam, pişmiş",
    "Rutabaga, raw": "İsveç şalgamı, çiğ",
    "Parsnip, raw": "Yaban havucu, çiğ",
    "Parsnip, cooked": "Yaban havucu, pişmiş",
    "Okra, raw": "Bamya, çiğ",
    "Okra, cooked": "Bamya, pişmiş",
    "Jalapeno, raw": "Jalapeño, çiğ",
    "Serrano pepper": "Serrano biber",
    "Habanero pepper": "Habanero biber",
    "Cucumber, pickled": "Salatalık turşusu",
    "Pumpkin, raw": "Kabak, çiğ",
    "Pumpkin, cooked": "Kabak, pişmiş",
    "Leek, raw": "Pırasa, çiğ",
    "Leek, cooked": "Pırasa, pişmiş",
    "Fennel, raw": "Rezene, çiğ",
    "Daikon radish": "Daikon turp",
    "Kohlrabi, raw": "Kohlrabi, çiğ",
    "Chives, raw": "Frenk soğanı, çiğ",
    "Mint, fresh": "Nane, taze",
    "Basil, fresh": "Fesleğen, taze",
    "Cilantro, raw": "Kişniş, çiğ",
    "Parsley, fresh": "Maydanoz, taze",

    # === Legumes & Nuts ===
    "Peanuts, raw": "Fıstık, çiğ",
    "Peanuts, roasted, salted": "Fıstık, kavrulmuş, tuzlu",
    "Peanuts, roasted, unsalted": "Fıstık, kavrulmuş, tuzsuz",
    "Almonds, raw": "Badem, çiğ",
    "Almonds, roasted, salted": "Badem, kavrulmuş, tuzlu",
    "Almonds, blanched": "Badem, haşlanmış",
    "Almonds, sliced": "Badem, dilimlenmiş",
    "Cashews, raw": "Kaju, çiğ",
    "Cashews, roasted, salted": "Kaju, kavrulmuş, tuzlu",
    "Walnuts, English": "Ceviz",
    "Walnuts, black": "Kara ceviz",
    "Pecans, raw": "Pekan cevizi, çiğ",
    "Pistachios, roasted, salted": "Antep fıstığı, kavrulmuş, tuzlu",
    "Pistachios, raw": "Antep fıstığı, çiğ",
    "Macadamia nuts, raw": "Makademya fındığı, çiğ",
    "Hazelnuts, raw": "Fındık, çiğ",
    "Brazil nuts, raw": "Brezilya cevizi, çiğ",
    "Pine nuts": "Çam fıstığı",
    "Sunflower seeds, raw": "Ayçiçeği çekirdeği, çiğ",
    "Pumpkin seeds (pepitas)": "Kabak çekirdeği",
    "Chia seeds": "Chia tohumu",
    "Flax seeds": "Keten tohumu",
    "Hemp seeds": "Kenevir tohumu",
    "Sesame seeds": "Susam",
    "Pumpkin seeds, white": "Kabak çekirdeği, beyaz",
    "Watermelon seeds": "Karpuz çekirdeği",
    "Peanut butter, creamy": "Fıstık ezmesi, kremali",
    "Peanut butter, chunky": "Fıstık ezmesi, parçalı",
    "Peanut butter, natural": "Fıstık ezmesi, doğal",
    "Peanut butter, powdered": "Fıstık ezmesi, toz",
    "Almond butter": "Badem ezmesi",
    "Cashew butter": "Kaju ezmesi",
    "Sunflower seed butter": "Ayçiçeği ezmesi",
    "Tahini, from hulled seeds": "Tahin, kabuksuz susam",
    "Tahini, from whole seeds": "Tahin, tam susam",
    "Black beans, cooked": "Siyah fasulye, pişmiş",
    "Black beans, canned, drained": "Siyah fasulye, konserve, süzülmüş",
    "Kidney beans, red, cooked": "Barbunya, kırmızı, pişmiş",
    "Kidney beans, red, canned": "Barbunya, kırmızı, konserve",
    "Pinto beans, cooked": "Pinto fasulye, pişmiş",
    "Pinto beans, canned": "Pinto fasulye, konserve",
    "Chickpeas (garbanzo), cooked": "Nohut, pişmiş",
    "Chickpeas, canned, drained": "Nohut, konserve, süzülmüş",
    "White beans, cooked": "Beyaz fasulye, pişmiş",
    "White beans, canned": "Beyaz fasulye, konserve",
    "Navy beans, cooked": "Kuru fasulye, pişmiş",
    "Lentils, green, cooked": "Mercimek, yeşil, pişmiş",
    "Lentils, red, cooked": "Mercimek, kırmızı, pişmiş",
    "Lentils, brown, cooked": "Mercimek, kahverengi, pişmiş",
    "Edamame, shelled, cooked": "Edamame, kabuksuz, pişmiş",
    "Edamame, in pod, cooked": "Edamame, baklavalı, pişmiş",
    "Peas, split, cooked": "Bezelye, bölünmüş, pişmiş",
    "Broad beans, cooked": "Bakla, pişmiş",
    "Butter beans, cooked": "Tereyağı fasulyesi, pişmiş",
    "Black-eyed peas, cooked": "Börülce, pişmiş",
    "Mung beans, cooked": "Maş fasulyesi, pişmiş",
    "Azuki beans, cooked": "Azuki fasulyesi, pişmiş",
    "Fava beans, cooked": "Bakla, pişmiş",
    "Lupini beans, cooked": "Lupin fasulyesi, pişmiş",
    "Mixed beans, canned": "Karışık fasulye, konserve",

    # === Oils & Fats ===
    "Olive oil, extra virgin": "Zeytinyağı, sızma",
    "Olive oil, virgin": "Zeytinyağı, natürel",
    "Olive oil, light": "Zeytinyağı, light",
    "Coconut oil": "Hindistan cevizi yağı",
    "Vegetable oil": "Bitkisel yağ",
    "Canola oil": "Kanola yağı",
    "Sesame oil": "Susam yağı",
    "Avocado oil": "Avokado yağı",
    "Peanut oil": "Fıstık yağı",
    "Sunflower oil": "Ayçiçeği yağı",
    "Safflower oil": "Aspir yağı",
    "Grapeseed oil": "Üzüm çekirdeği yağı",
    "Walnut oil": "Ceviz yağı",
    "Flaxseed oil": "Keten tohumu yağı",
    "MCT oil": "MCT yağı",
    "Mustard seed oil": "Hardal yağı",
    "Mayonnaise, regular": "Mayonez, normal",
    "Mayonnaise, light": "Mayonez, light",
    "Mayonnaise, olive oil based": "Mayonez, zeytinyağlı",
    "Margarine, regular": "Margarin, normal",
    "Margarine, light": "Margarin, light",
    "Ghee (clarified butter)": "Sade yağ",
    "Lard": "İç yağı (domuz)",
    "Shortening, vegetable": "Bitkisel katı yağ",
    "Cooking spray": "Pişirme spreyi",

    # === Snacks & Sweets ===
    "Dark chocolate, 70% cacao": "Bitter çikolata, %70 kakao",
    "Dark chocolate, 85% cacao": "Bitter çikolata, %85 kakao",
    "Dark chocolate, 90% cacao": "Bitter çikolata, %90 kakao",
    "Milk chocolate": "Sütlü çikolata",
    "Milk chocolate with almonds": "Sütlü çikolata, bademli",
    "White chocolate": "Beyaz çikolata",
    "Chocolate chips, semi-sweet": "Çikolata parçaları, yarı tatlı",
    "Chocolate chips, dark": "Çikolata parçaları, bitter",
    "Chocolate candy bar, general": "Çikolatalı şeker bar",
    "Chocolate covered nuts": "Çikolata kaplı kuruyemiş",
    "Honey": "Bal",
    "Maple syrup": "Akçaağaç şurubu",
    "Agave nectar": "Agave nektarı",
    "Corn syrup": "Mısır şurubu",
    "Brown sugar": "Esmer şeker",
    "White granulated sugar": "Beyaz şeker",
    "Jelly, grape": "Jöle, üzüm",
    "Jam, strawberry": "Reçel, çilek",
    "Jam, raspberry": "Reçel, ahududu",
    "Peanut butter cups": "Fıstık ezmeli çikolata",
    "Granola bar, low fat": "Granola bar, az yağlı",
    "Granola bar, regular": "Granola bar, normal",
    "Granola bar, chocolate": "Granola bar, çikolatalı",
    "Protein bar, vanilla": "Protein bar, vanilyalı",
    "Protein bar, chocolate": "Protein bar, çikolatalı",
    "Protein bar, cookies and cream": "Protein bar, kurabiye kremalı",
    "Energy bar": "Enerji barı",
    "Chips, potato, regular": "Cips, patates, normal",
    "Chips, potato, light": "Cips, patates, light",
    "Chips, tortilla, plain": "Cips, tortilla, sade",
    "Chips, tortilla, cheese": "Cips, tortilla, peynirli",
    "Chips, vegetable": "Cips, sebze",
    "Pretzels, twisted": "Pretzel",
    "Candy, gummy bears": "Şeker, jöleli ayıcık",
    "Candy, hard candy": "Sert şeker",
    "Candy, licorice": "Meyan kökü şekeri",
    "Candy, taffy": "Taffy şeker",
    "Candy, lollipop": "Lolipop",
    "Candy, caramel": "Karamel şeker",
    "Candy, fudge": "Fudge",
    "Cookie, chocolate chip": "Kurabiye, çikolatalı",
    "Cookie, oatmeal raisin": "Kurabiye, yulaf kuru üzümlü",
    "Cookie, sugar": "Kurabiye, şekerli",
    "Cookie, shortbread": "Kurabiye, sade",
    "Cookie, fortune": "Fal kurabiyesi",
    "Brownie": "Brownie",
    "Donut, glazed": "Donut, şekerli",
    "Donut, chocolate": "Donut, çikolatalı",
    "Donut, jelly-filled": "Donut, reçelli",
    "Muffin, blueberry, store-bought": "Muffin, yaban mersinli",
    "Cake, vanilla": "Kek, vanilyalı",
    "Cake, chocolate": "Kek, çikolatalı",
    "Cake, carrot": "Kek, havuçlu",
    "Cake, cheesecake": "Cheesecake",
    "Pie, apple": "Turta, elmalı",
    "Pie, pumpkin": "Turta, kabak",
    "Trail mix": "Karışık kuruyemiş",
    "Popcorn, candy coated": "Patlamış mısır, şekerli",
    "Peppermint candy": "Nane şekeri",
    "Dates, stuffed": "Doldurulmuş hurma",

    # === Beverages ===
    "Coffee, brewed, black": "Kahve, demlenmiş, sade",
    "Espresso": "Espresso",
    "Americano": "Americano",
    "Latte, whole milk": "Latte, tam yağlı süt",
    "Latte, 2% milk": "Latte, %2 yağlı süt",
    "Latte, skim milk": "Latte, yağsız süt",
    "Latte, soy milk": "Latte, soya sütü",
    "Cappuccino, whole milk": "Cappuccino, tam yağlı süt",
    "Cappuccino, 2% milk": "Cappuccino, %2 yağlı süt",
    "Macchiato": "Macchiato",
    "Mocha, whole milk": "Mocha, tam yağlı süt",
    "Flat white": "Flat white",
    "Cortado": "Cortado",
    "Tea, black, brewed": "Çay, siyah, demlenmiş",
    "Tea, green, brewed": "Çay, yeşil, demlenmiş",
    "Tea, white, brewed": "Çay, beyaz, demlenmiş",
    "Tea, oolong, brewed": "Çay, oolong, demlenmiş",
    "Tea, herbal, brewed": "Bitki çayı, demlenmiş",
    "Tea, matcha, prepared with water": "Matcha çayı",
    "Tea, chai latte": "Çay latte (masala)",
    "Orange juice, fresh squeezed": "Portakal suyu, taze sıkılmış",
    "Orange juice, from concentrate": "Portakal suyu, konsantreden",
    "Lemonade, fresh": "Limonata, taze",
    "Limeade, fresh": "Misket limonu suyu, taze",
    "Vegetable juice, mixed": "Sebze suyu, karışık",
    "Tomato juice": "Domates suyu",
    "Carrot juice": "Havuç suyu",
    "Beet juice": "Pancar suyu",
    "Celery juice": "Kereviz suyu",
    "Ginger juice, fresh": "Zencefil suyu, taze",
    "Wheatgrass juice": "Buğday çimi suyu",
    "Soda, cola, regular": "Kola, normal",
    "Soda, cola, diet": "Kola, diyet",
    "Soda, lemon-lime, regular": "Gazoz, limonlu, normal",
    "Soda, lemon-lime, diet": "Gazoz, limonlu, diyet",
    "Soda, root beer": "Kök bira gazoz",
    "Soda, ginger ale": "Zencefil gazoz",
    "Soda, orange": "Portakallı gazoz",
    "Soda, grape": "Üzümlü gazoz",
    "Energy drink, typical": "Enerji içeceği",
    "Sports drink, typical": "Spor içeceği",
    "Coconut water": "Hindistan cevizi suyu",
    "Kombucha, plain": "Kombucha, sade",
    "Kombucha, flavored": "Kombucha, aromalı",
    "Beer, regular": "Bira, normal",
    "Beer, light": "Bira, light",
    "Beer, IPA": "Bira, IPA",
    "Beer, stout": "Bira, stout",
    "Wine, red": "Şarap, kırmızı",
    "Wine, white": "Şarap, beyaz",
    "Wine, rosé": "Şarap, roze",
    "Wine, sparkling": "Şarap, köpüklü",
    "Champagne": "Şampanya",
    "Vodka": "Votka",
    "Whiskey": "Viski",
    "Rum": "Rom",
    "Gin": "Cin",
    "Tequila": "Tekila",
    "Brandy": "Brendi",
    "Liqueur": "Likör",
    "Smoothie, berry, store-bought": "Smoothie, meyveli",
    "Smoothie, tropical, store-bought": "Smoothie, tropikal",
    "Protein shake, vanilla": "Protein shake, vanilyalı",
    "Protein shake, chocolate": "Protein shake, çikolatalı",
    "Protein shake, strawberry": "Protein shake, çilekli",

    # === Condiments & Sauces ===
    "Ketchup": "Ketçap",
    "Mustard, yellow": "Hardal, sarı",
    "Mustard, Dijon": "Hardal, Dijon",
    "Mustard, spicy brown": "Hardal, acı kahverengi",
    "Soy sauce": "Soya sosu",
    "Soy sauce, low sodium": "Soya sosu, az tuzlu",
    "Tamari sauce": "Tamari sosu",
    "Hot sauce, generic": "Acı sos",
    "Hot sauce, sriracha": "Sriracha sos",
    "Hot sauce, habanero": "Habanero sos",
    "Hot sauce, cayenne": "Cayenne sos",
    "Barbecue sauce": "Barbekü sosu",
    "BBQ sauce, low sugar": "Barbekü sosu, az şekerli",
    "Ranch dressing": "Ranch sos",
    "Ranch dressing, light": "Ranch sos, light",
    "Italian dressing": "İtalyan sosu",
    "Italian dressing, light": "İtalyan sosu, light",
    "Caesar dressing": "Sezar sosu",
    "Caesar dressing, light": "Sezar sosu, light",
    "Balsamic vinaigrette": "Balzamik sos",
    "Vinaigrette, olive oil based": "Zeytinyağlı sos",
    "Salsa, fresh": "Salsa, taze",
    "Salsa, red": "Salsa, kırmızı",
    "Salsa, verde": "Salsa verde",
    "Salsa, corn": "Salsa, mısırlı",
    "Hummus, classic": "Humus, klasik",
    "Hummus, roasted garlic": "Humus, fırında sarımsaklı",
    "Hummus, roasted red pepper": "Humus, kırmızı biberli",
    "Guacamole": "Guacamole",
    "Guacamole, light": "Guacamole, light",
    "Teriyaki sauce": "Teriyaki sosu",
    "Worcestershire sauce": "Worcestershire sosu",
    "Fish sauce": "Balık sosu",
    "Pesto, basil": "Pesto, fesleğenli",
    "Marinara sauce": "Marinara sosu",
    "Alfredo sauce": "Alfredo sosu",
    "Buffalo sauce": "Buffalo sosu",
    "Relish, sweet": "Relish, tatlı",
    "Olives, green, pitted": "Yeşil zeytin, çekirdeksiz",
    "Olives, black, pitted": "Siyah zeytin, çekirdeksiz",
    "Pickles, dill": "Turşu, dereotlu",
    "Pickle juice": "Turşu suyu",
    "Capers": "Kapari",
    "Sesame paste (tahini)": "Tahin",
    "Miso, white": "Miso, beyaz",
    "Miso, red": "Miso, kırmızı",
    "Soy butter": "Soya ezmesi",
    "Coconut aminos": "Hindistan cevizi aminoası",
    "Liquid smoke": "Sıvı duman aroması",

    # === Prepared Foods ===
    "Hamburger patty, 1/4 lb": "Hamburger köfte, 115g",
    "Cheeseburger, 1/4 lb": "Cheeseburger, 115g",
    "Hamburger, double": "Çift köfteli hamburger",
    "Hot dog, beef": "Sosis (hot dog), dana",
    "Hot dog, chicken": "Sosis (hot dog), tavuk",
    "Hot dog with chili": "Sosis (hot dog), soslu",
    "French fries, frozen, baked": "Patates kızartması, dondurulmuş, fırında",
    "French fries, frozen, fried": "Patates kızartması, dondurulmuş, yağda",
    "French fries, fast food": "Patates kızartması, fast food",
    "Sweet potato fries": "Tatlı patates kızartması",
    "Chicken nuggets": "Tavuk nugget",
    "Chicken wings, Buffalo": "Tavuk kanadı, Buffalo",
    "Fried chicken, drumstick": "Kızarmış tavuk, incik",
    "Fried chicken, thigh": "Kızarmış tavuk, but",
    "Fried chicken, breast": "Kızarmış tavuk, göğüs",
    "Quesadilla": "Quesadilla",
    "Enchilada": "Enchilada",
    "Burrito bowl, chicken": "Burrito kase, tavuklu",
    "Ramen noodles": "Ramen noodle",
    "Pho": "Pho çorbası",
    "Lo mein": "Lo mein",
    "Fried rice": "Kızarmış pirinç",
    "Mac and cheese": "Makarna ve peynir",
    "Lasagna, meat": "Lazanya, etli",
    "Lasagna, vegetarian": "Lazanya, vejetaryen",
    "Garden salad": "Bahçe salatası",
    "Oatmeal, plain, prepared": "Yulaf lapası, sade",
    "Oatmeal, with berries": "Yulaf lapası, meyveli",
    "Oatmeal, with nuts": "Yulaf lapası, cevizli",
    "Scrambled eggs, 2 eggs": "Çırpılmış yumurta, 2 yumurta",
    "Fried eggs, 2 eggs": "Sahanda yumurta, 2 yumurta",
    "Boiled eggs, 2 eggs": "Haşlanmış yumurta, 2 yumurta",
    "Omelet, plain, 2 eggs": "Omlet, sade, 2 yumurta",
    "Omelet, cheese, 2 eggs": "Omlet, peynirli, 2 yumurta",
    "Omelet, vegetable, 2 eggs": "Omlet, sebzeli, 2 yumurta",
    "Omelet, meat, 2 eggs": "Omlet, etli, 2 yumurta",
    "Pancakes, 2, with syrup": "Krep, 2 adet, şuruplu",
    "Pancakes, 2, with butter and syrup": "Krep, 2 adet, tereyağlı şuruplu",
    "Waffles, 2, with syrup": "Waffle, 2 adet, şuruplu",
    "Waffles, 2, with butter and syrup": "Waffle, 2 adet, tereyağlı şuruplu",
    "French toast": "Fransız tostu",
    "Crepes, plain": "Krep, sade",
    "Crepes with chocolate": "Krep, çikolatalı",
    "Hash browns, frozen": "Hash brown, dondurulmuş",
    "Hash browns, homemade": "Hash brown, ev yapımı",
    "Breakfast sandwich": "Kahvaltı sandviç",
    "Granola with yogurt": "Granola ve yoğurt",
    "Yogurt parfait": "Yoğurt parfait",
    "Protein pancakes": "Proteinli krep",
}

# Pizza / Taco / Burrito / Sushi variants — same base name with different full names in CSV
PIZZA_TR = {
    "Pizza, cheese, 1 slice (1/8 of 12 inch)": "Pizza, peynirli, 1 dilim",
    "Pizza, pepperoni, 1 slice (1/8 of 12 inch)": "Pizza, pepperonili, 1 dilim",
}
TACO_TR = {
    "Taco, beef, hard shell": "Taco, etli, sert",
    "Taco, chicken, soft shell": "Taco, tavuklu, yumuşak",
    "Taco, fish": "Taco, balıklı",
}
BURRITO_TR = {
    "Burrito, beef and bean": "Burrito, etli ve fasulyeli",
    "Burrito, chicken": "Burrito, tavuklu",
    "Burrito, vegetarian": "Burrito, vejetaryen",
}
SUSHI_TR = {
    "Sushi roll, California roll": "Sushi, California roll",
    "Sushi roll, spicy tuna": "Sushi, baharatlı ton balıklı",
    "Sushi roll, salmon avocado": "Sushi, somonlu avokadolu",
    "Sushi roll, cucumber": "Sushi, salatalıklı",
    "Sushi roll, shrimp tempura": "Sushi, karidesli tempura",
    "Nigiri sushi, salmon": "Nigiri sushi, somonlu",
    "Nigiri sushi, tuna": "Nigiri sushi, ton balıklı",
    "Nigiri sushi, shrimp": "Nigiri sushi, karidesli",
}

def get_tr(name):
    if name in TRANSLATIONS:
        return TRANSLATIONS[name]
    if name in PIZZA_TR:
        return PIZZA_TR[name]
    if name in TACO_TR:
        return TACO_TR[name]
    if name in BURRITO_TR:
        return BURRITO_TR[name]
    if name in SUSHI_TR:
        return SUSHI_TR[name]
    # Bread/Bagel/Tortilla/etc variants — look for base word match
    base_map = {
        "Bread": "Ekmek",
        "Bagel": "Simit (bagel)",
        "English muffin": "İngiliz muffin",
        "Croissant": "Kruvasan",
        "Tortilla": "Tortilla",
        "Pita bread": "Pide ekmeği",
        "Rice cakes": "Pirinç keki",
        "Crackers": "Kraker",
        "Pancake": "Krep (pancake)",
        "Waffle": "Waffle",
        "Pizza": "Pizza",
        "Taco": "Taco",
        "Burrito": "Burrito",
        "Quesadilla": "Quesadilla",
        "Sushi roll": "Sushi",
        "Nigiri sushi": "Nigiri sushi",
        "Mac and cheese": "Makarna ve peynir",
        "Cooking spray": "Pişirme spreyi",
    }
    for base, tr in base_map.items():
        if name == base or name.startswith(base + ",") or name.startswith(base + " "):
            return tr
    return ""

def main():
    csv_path = os.path.join(os.path.dirname(__file__), "foods.csv")
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
        fieldnames = list(rows[0].keys())

    # Add name_tr column after name if not present
    if "name_tr" not in fieldnames:
        idx = fieldnames.index("name") + 1
        fieldnames.insert(idx, "name_tr")

    matched = 0
    for row in rows:
        tr = get_tr(row["name"])
        row["name_tr"] = tr
        if tr:
            matched += 1

    print(f"Total: {len(rows)}, Translated: {matched}, Missing: {len(rows)-matched}")
    missing = [r["name"] for r in rows if not r.get("name_tr")]
    if missing:
        print("Missing translations:")
        for m in missing:
            print(f"  {repr(m)}")

    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)

    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        f.write(out.getvalue())

    print("Done.")

if __name__ == "__main__":
    main()
